const getCategory = {
  'Top Stories': 'Main Feeds',
  'Most Recent Stories': 'Main Feeds',
  India: 'Main Feeds',
  World: 'Main Feeds',
  NRI: 'Main Feeds',
  Business: 'Main Feeds',
  Cricket: 'Main Feeds',
  Sports: 'Main Feeds',
  Health: 'Main Feeds',
  Science: 'Main Feeds',
  Environment: 'Main Feeds',
  Tech: 'Main Feeds',
  Education: 'Main Feeds',
  'Sunday TOI': 'Main Feeds',
  Opinion: 'Main Feeds',
  Entertainment: 'Main Feeds',
  'Life & Style': 'Main Feeds',
  'Most Read': 'Main Feeds',
  'Most Shared': 'Main Feeds',
  'Most Commented': 'Main Feeds',

  Mumbai: 'Cities',
  Delhi: 'Cities',
  Bangalore: 'Cities',
  Hyderabad: 'Cities',
  Chennai: 'Cities',
  Ahemdabad: 'Cities',
  Allahabad: 'Cities',
  Bhubaneswar: 'Cities',
  Coimbatore: 'Cities',
  Gurgaon: 'Cities',
  Guwahati: 'Cities',
  Hubli: 'Cities',
  Kanpur: 'Cities',
  Kolkata: 'Cities',
  Ludhiana: 'Cities',
  Mangalore: 'Cities',
  Mysore: 'Cities',
  Noida: 'Cities',
  Pune: 'Cities',
  Goa: 'Cities',
  Chandigarh: 'Cities',
  Lucknow: 'Cities',
  Patna: 'Cities',
  Jaipur: 'Cities',
  Nagpur: 'Cities',
  Rajkot: 'Cities',
  Ranchi: 'Cities',
  Surat: 'Cities',
  Vadodara: 'Cities',
  Varanasi: 'Cities',
  Thane: 'Cities',
  Thiruvananthapuram: 'Cities',

  US: 'World',
  NRI: 'World',
  Pakistan: 'World',
  'South Asia': 'World',
  UK: 'World',
  Europe: 'World',
  China: 'World',
  'Middle East': 'World',
  'Rest of World': 'World',
  'Mad, Mad World': 'World',
};

module.exports = {
  getCategory: getCategory,
};
